template_path: templates/DynamoDB-Table.py
sceptre_user_data:
  HashKeyElementName: cloudTable
  HashKeyElementType: S
  ReadCapacityUnits: 5
  WriteCapacityUnits: 5
parameters:
  HashKeyElementName: cloudTable
  HashKeyElementType: S