template_path: templates/DynamoDB-Table.py
parameters:
  HashKeyElementName: cloudTable
  HashKeyElementType: S
  ReadCapacityUnits: '5'
  WriteCapacityUnits: '5'
  # hashkeyname: cloud-table
  # hashkeytype: S
  # readunits: 5
  # writeunits: 5